# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Tue Jan 19 22:49:14 2021
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import addonHandler
# end wxGlade


class crypto_infoFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: crypto_infoFrame.__init__
        try: addonHandler.initTranslation()
        except: pass
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle(_("crypto_info"))
        self.SetFocus()

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.refresh_button = wx.Button(self.panel_1, wx.ID_ANY, _("Refresh"))
        sizer_1.Add(self.refresh_button, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.crypto_list_ctrl = wx.ListCtrl(self.panel_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.crypto_list_ctrl.SetFocus()
        self.crypto_list_ctrl.AppendColumn(_("Name"), format=wx.LIST_FORMAT_LEFT, width=-1)
        self.crypto_list_ctrl.AppendColumn(_("Price"), format=wx.LIST_FORMAT_LEFT, width=-1)
        self.crypto_list_ctrl.AppendColumn(_("Change percent in 24 h"), format=wx.LIST_FORMAT_LEFT, width=-1)
        self.crypto_list_ctrl.AppendColumn(_("Capitalization"), format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer_1.Add(self.crypto_list_ctrl, 1, wx.EXPAND | wx.LEFT, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT, 0)

        self.ok_button = wx.Button(self.panel_1, wx.ID_ANY, _("OK"))
        self.ok_button.SetDefault()
        sizer_2.Add(self.ok_button, 0, 0, 0)

        self.cancel_button = wx.Button(self.panel_1, wx.ID_ANY, _("Cancel"))
        self.cancel_button.SetDefault()
        sizer_2.Add(self.cancel_button, 0, 0, 0)

        sizer_2.Realize()

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.onrefresh, self.refresh_button)
        self.Bind(wx.EVT_BUTTON, self.onok, self.ok_button)
        self.Bind(wx.EVT_BUTTON, self.oncancel, self.cancel_button)
        # end wxGlade

    def onrefresh(self, event):  # wxGlade: crypto_infoFrame.<event_handler>
        print("Event handler 'onrefresh' not implemented!")
        event.Skip()

    def onok(self, event):  # wxGlade: crypto_infoFrame.<event_handler>
        print("Event handler 'onok' not implemented!")
        event.Skip()

    def oncancel(self, event):  # wxGlade: crypto_infoFrame.<event_handler>
        print("Event handler 'oncancel' not implemented!")
        event.Skip()

# end of class crypto_infoFrame
